version: "3.8"
services:
  app:
    build: .
    ports:
      - "${DOCKER_COMPOSE_HOST}:${DOCKER_COMPOSE_PORT}:${PORT}"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0 # binds to docker internal app host
